import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl overflow-y-auto px-6 py-16">
      <Link
        href="/"
        className="mb-8 inline-block text-sm text-muted-foreground hover:text-foreground"
      >
        &larr; Back to C3.chat
      </Link>

      <h1 className="mb-2 text-3xl font-bold tracking-tight">
        Terms of Service
      </h1>
      <p className="mb-10 text-sm text-muted-foreground">
        Last updated: March 13, 2026
      </p>

      <div className="prose prose-neutral dark:prose-invert prose-headings:font-semibold prose-headings:tracking-tight max-w-none">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using C3.chat (&quot;the Service&quot;), operated by
          Crafter Station, you agree to be bound by these Terms of Service. If
          you do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          C3.chat is a multi-model AI chat interface that allows users to
          interact with various large language models. The Service is provided
          &quot;as is&quot; and is currently in beta.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You may use the Service without an account subject to daily usage
          limits. Creating an account unlocks additional features. You are
          responsible for maintaining the security of your account credentials.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to bypass rate limits or usage restrictions</li>
          <li>
            Transmit harmful, abusive, or otherwise objectionable content
          </li>
          <li>
            Reverse engineer, decompile, or disassemble any part of the Service
          </li>
          <li>
            Use the Service to develop competing products or services
          </li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Responses are generated by third-party AI models. Crafter Station does
          not guarantee the accuracy, completeness, or reliability of
          AI-generated content. You are solely responsible for how you use any
          output from the Service.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          You retain ownership of the content you submit. AI-generated responses
          are provided for your use without claim of ownership by Crafter
          Station. The Service itself, including its design, code, and branding,
          remains the property of Crafter Station.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Crafter Station shall not be
          liable for any indirect, incidental, special, or consequential damages
          arising from your use of the Service, including but not limited to
          reliance on AI-generated content.
        </p>

        <h2>8. Modifications</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use
          of the Service after changes constitutes acceptance of the updated
          terms.
        </p>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at our
          discretion, with or without cause, at any time.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions about these terms? Reach us at{" "}
          <a href="mailto:hello@crafterstation.com">hello@crafterstation.com</a>.
        </p>
      </div>
    </main>
  );
}
